### PR TITLE
OWL-2969: Gateway Star Fix

### PR DESCRIPTION
**Pull request by chaospeach**
https://jira.uwo.ca/browse/OWL-2969

Replaced icon with a globe which is fairly standard in Gateway

### CODE REVIEW

**Comment by plukasew** [comment]
Not sure about the globe, that's generally used to indicate external links. My first thought is the house icon but that's the same as the Home site. Maybe some kind of gateway/doorway/portal icon?

**Comment by chaospeach** [comment]
Unfortunately there isn't a gateway/door icon. But I'll see what I can find in the font-awesome library.

**Review by plukasew — APPROVED** [review]
Looks okay to me.

**Comment by fostersdesign** [comment]
We are using fa-university for the EZProxy Link. I would like to see what it looks like in the top nav.

**Comment by plukasew** [comment]
It's merged now so pull it down and take a look. If we find another icon we like better, we can always swap it out later.

**Pull request merged**
